# Generated by Django 5.2.4 on 2025-07-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('roll_no', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('marks', models.FloatField()),
                ('subject', models.CharField(max_length=100)),
            ],
        ),
    ]
